### ISSUE TITLE
image links?

### ISSUE THREAD

**Issue by EmVee381** [WnP/vimwiki_markdown#22]
Hello, i am trying to convert my markdown vim wiki with this script, but it does not support image links? 

i tried syntax
Inline link: >
```
  [Looks like this](URL)
```
Image link: >
```  
![Looks like this](URL)
```
for jpg files
first made links to image.jpg.html

second skipped link at all.

can you help me in some way? 

thx

**Comment by WnP** [comment]
Hi @EmVee381,

I'm actually using images in my own wiki, by the way I don't understand your use case, can you use github code syntax to clarify it?

Thx in advance

**Comment by EmVee381** [comment]
sorry edited :) do you use images on local filesystem ? i forgot to say that... as i have files stored in subdirectory of wiki root and i am linking images from these subdirectories, with syntax from my first post....

**Comment by WnP** [comment]
Local images should be present in your `site_html` directory an use relative path to this one. otherwise you should use absolute path to your image.

All image formats supported by your browser are supported.

Use markdown syntax to render your image: https://www.markdownguide.org/basic-syntax/#images-1

**Comment by EmVee381** [comment]
thx, absolute paths solved my problem

thank you for your time
