### ISSUE TITLE
Convert vimwiki automatic links to Markdown syntax

### ISSUE THREAD

**Issue by cweagans** [WnP/vimwiki_markdown#4]
If I use `:VimwikiGenerateLinks`, it creates a bunch of links like this:

```
- [[foo]]
- [[bar]]
```

As far as I can see, there's not a way to get vimwiki to generate markdown-formatted links. Is that something that this script could handle gracefully?

**Comment by WnP** [comment]
Hi @cweagans,

[VimwikiGenerateLinks](https://github.com/vimwiki/vimwiki/blob/master/ftplugin/vimwiki.vim#L262) call [vimwiki#base#generate_links](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L385) which is a pure vim script function. So there's no way for this project to handle that feature.

By the way [it looks like there's some markdown support](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L408) if you set `vimwiki#vars#get_wikilocal('syntax')` to `markdown` it *may* do what you want - not tested.

I'm closing this issue because it's out of the scope of this project. Feel free to open a new one on [vimwiki](https://github.com/vimwiki/vimwiki/issues) to get support on this feature.

Hope this help.
