### ISSUE TITLE
Exporting HTML does not provide pygmentize.css

### ISSUE THREAD

**Issue by seqizz** [WnP/vimwiki_markdown#5]
Hi there,

First of all, thanks for this plugin. I owe you [my wiki](https://gurkan.in/wiki/) :slightly_smiling_face: 

One small issue I've realized: After exporting to HTML, the pygmentize.css file in the target folder is missing. Exact issue I'm getting on nginx logs:

```
*6382 open() "/shared/vhosts/gurkan.in/public/wiki/pygmentize.css" failed (2: No such file or directory), client: 50.100.227.44, server: gurkan.in, request: "GET /wiki/pygmentize.css HTTP/2.0", host: "gurkan.in", referrer: "https://gurkan.in/wiki/nix.html"
```

So I've manually generated the file like you told on README. I'm not sure if this is expected or not? Can I somehow add an extra parameter to make HTML generation also run the pygments command to generate the required css?

Thanks!

**Comment by WnP** [comment]
Hi @seqizz,

Yes this is the expected behavior, the CSS file in this repository is just an example as the HTML template.

If you want to generate it during each build you can just provide a simple shell script to do that and use it in place of `'custom_wiki2html': 'vimwiki_markdown'`, eg.:

```sh
#!/bin/sh
pygmentize -S default -f html -a .codehilite > /path/to/styles.css
vimwiki_markdow "$@"
```

Something like that. (note that you can even use `$4` which is the output directory)

Thanks for your interest on the project :-)
