### ISSUE TITLE
Can't get latex formula to display on html file

### ISSUE THREAD

**Issue by PedroVSCoimbra** [WnP/vimwiki_markdown#6]
I'm able to get latex formula using the vimwiki syntax, but when I use vimwiki_markdown and markdown syntax the equations don not show up. Is it possible to get them using this converter?

**Comment by WnP** [comment]
Hi @PedroVSCoimbra,

Can you give an example? with input data and expected `html` output.

Thanks

**Comment by WnP** [comment]
@PedroVSCoimbra [vimwiki use MathJax](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L1358-L1361) to render formula as SVG, so you just need to add MathJax requirements in you html header section:

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```
See [vimwiki documentation to change the default template](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L2213).

See [MathJax documentation](https://www.mathjax.org/) if you want more information about MathJax.

I'm closing this issue since it's up to you to activate this feature, feel free to reopen if you have more question.
